### ISSUE TITLE
Team mailboxes over IMAP

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1272]
Following the merge of https://github.com/apache/james-project/pull/2445

Write a `TwakeMailNamespaceSupplier` and a `TwakeMailMailboxNameConverter` that would...

 - Treat `#private.xxx` and directly `xxx` as user private  
 - Treat `#user.bob.xxx` as other user mailboxes
 - Treat `#team-mailbox.marketting.xxx` as a shared mailbox

## Definition of done

 - [ ] In depth unit tests for `TwakeMailNamespaceSupplier` and `TwakeMailMailboxNameConverter`

 - [ ] This changeset would test in depth the `NAMESPACE` and `LIST`. Other commands can be lightly tested (status command only is OK). We can mimic ImapServerTest but on top of a Twake mail memory server.

**Comment by chibenwa** [comment]
Spotted on `imap.linagora.com`

```
org.apache.james.imap.main.DeniedAccessOnSharedMailboxException: null
	at org.apache.james.imap.main.PathConverter$Default.asMailboxPath(PathConverter.java:119)
	at org.apache.james.imap.main.PathConverter$Default.buildAbsolutePath(PathConverter.java:97)
	at org.apache.james.imap.main.PathConverter$Default.buildFullPath(PathConverter.java:81)
	at org.apache.james.imap.processor.AbstractSelectionProcessor.processRequestReactive(AbstractSelectionProcessor.java:105)
	at org.apache.james.imap.processor.AbstractSelectionProcessor.processRequestReactive(AbstractSelectionProcessor.java:82)
	at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:98)
	at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:75)
	at org.apache.james.imap.processor.base.AbstractProcessor.processReactive(AbstractProcessor.java:52)
	at org.apache.james.imap.processor.DefaultProcessor.processReactive(DefaultProcessor.java:158)
	at org.apache.james.imapserver.netty.ImapChannelUpstreamHandler.channelRead(ImapChannelUpstreamHandler.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Asking the user, we spotted halth exposed team mailboxes over IMAP

Thus this becomes a priority topic.

**Comment by vttranlina** [comment]
wip pr https://github.com/linagora/tmail-backend/pull/1311

**Comment by chibenwa** [comment]
It is a simple fix to disable them in LIST mailbox when using default naming scheme
