### ISSUE TITLE
APISIX - Authentik - OIDC - X-User

### ISSUE THREAD

**Issue by NumeriKa** [linagora/tmail-backend#1287]
### Description of the bug

I'm trying to setup twake-mail stack with authentik acting as OIDC provider. I'm using the demo compose file, with some modification regarding ldap and sso configuration.

I'm using authentik acting as OIDC provider and LDAP server with outpost configuration. I'm able to get redirected to authentik for authentication, and get a working access token.

The issue is on last step, when trying to acces to /oidc/jmap/session - i get and 401 Unauthorized.

I realize that APISIX pluggin is working with UUID to pass the email address to james. On the demo configuration UUID is equal to mail user address.

On authentik, UUID is a common string value and it's not corresponding to the user email address. So apache james is not able to verify the identity of the current logged user on ldap.

"org.apache.james.user.api.InvalidUsernameException: Given Username needs to contain a @domainpart"

### Reproduction Steps

Change the UUID on the ldap configuration  (populate.ldif) as standard UUID string and try to login with the user.

### Expected result

On APISIX side, i'm expected to have the email address send on the X-User header instead of the UUID

### Context

Working on demo setup with the last docker compose file and image.

### Additional information

tcpdump Header request 

```
09:46:56.050594 IP 192.168.208.4.33306 > 192.168.208.2.http: Flags [P.], seq 5520:9768, ack 1131, win 501, options [nop,nop,TS val 657637820 ecr 795057803], length 4248: HTTP: GET /jmap/session HTTP/1.1
E...Y@@.@..............P............2......
'2../c..GET /jmap/session HTTP/1.1
Host: apisix.example.com:9080
X-Real-IP: 10.0.50.6
X-Forwarded-For: 10.0.50.6
X-Forwarded-Proto: http
X-Forwarded-Host: apisix.example.com
X-Forwarded-Port: 9080
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWQ0YmNkZjFjMjkwZGEwMGY0ZDE2OTliZjFmNDQ0IiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwOi8vc3NvLmV4YW1wbGUuY29tL2FwcGxpY2F0aW9uL28vYXBwX3NtYXNoLW1haWwvIiwic3ViIjoiOGQ2NWZhNzQ5YzU3NDJhMmJhMTgzM2JiOWE4NzUwMDQ3YjU2MGQxZWM4NmMyYzI0ZTNjOTBlZjU0ZGZlYWEwZCIsImF1ZCI6ImphbWVzIiwiZXhwIjoxNzMwODg2NzEzLCJpYXQiOjE3MzA4ODY0MTMsImF1dGhfdGltZSI6MTczMDg4NjM5OSwiYWNyIjoiZ29hdXRoZW50aWsuaW8vcHJvdmlkZXJzL29hdXRoMi9kZWZhdWx0IiwiYW1yIjpbInB3ZCJdLCJlbWFpbCI6ImphbWVzLXVzZXJAdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJKYW1lcyIsImdpdmVuX25hbWUiOiJKYW1lcyIsInByZWZlcnJlZF91c2VybmFtZSI6ImphbWVzLXVzZXIiLCJuaWNrbmFtZSI6ImphbWVzLXVzZXIiLCJncm91cHMiOlsiZmlhdF9zbWFzaC1tYWlsIl0sImF6cCI6ImphbWVzIiwidWlkIjoiQlozU1VvZ0F5QUQ4YlV6b3BrWkxvRHdEbTk1cDhmYnZLOUQ5bk5aZSJ9.bmW9lbRE59FSCkajKtrL0ukk8uOzhbMminxXFVM6tyHv_x70zY096DuOf7dlCRsPERh_NYG27rPIGsbsAH2YHhwIoE1NLJ24NLnHDjljs7n8qrfB1T6_Sipr0MISkNU5OP5RLBZeh0_BNLhLVL9n8s7cd_dWxWcV9O8Q5hbsTndzjm8Avvi_ckhsmI0RphNQxHSZGMtr2opz_dx-x5PMJsEgTJr0G6Q0fA6cz3cL6UD3AcGCzAMLz3upEGlfMJyHFf88T7c670k500VW3oMoSfU7KskpbwnlbES028MDG1IYvB6esEE7-Dr10hlTuSC_UhJCK1K86-MlPOpfk3YrTp9DFglFQpUtF7P1v8PFZVwOqY1cscvgBEEWkK-qqPzE7qkz7olNZV61mOJIbOcPyrQeKHClQUk9-pIOJfY3Ve438_5eYZ3sQuHCksCthN8hLSmjwe-u2K3uxUTMTcz5zya7Co8im0vycucvgYk_56sbY69RFtW9LK-ZTuMprg3dWUzjYOQKGgQTJBo75I630Jm-VoxEnIU4pWL-njFY-8ISQNvSTvH_SibzL5Wly5oKZcdsTWvvhUZ4DRs2QXBNp1XR1JsS2quZxtC0ejiZ5QWtMwsS22Ni1TtA_A1xv9RBAGKwCUf5u6vf7MQTm0P9P0ozESN9E0_9MYIEJcc3fwA
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
accept: application/json;jmapVersion=rfc-8621
content-type: application/json
Referer: http://test.sso.example.com:8080/
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
X-Access-Token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1MWQ0YmNkZjFjMjkwZGEwMGY0ZDE2OTliZjFmNDQ0IiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwOi8vc3NvLmV4YW1wbGUuY29tL2FwcGxpY2F0aW9uL28vYXBwX3NtYXNoLW1haWwvIiwic3ViIjoiOGQ2NWZhNzQ5YzU3NDJhMmJhMTgzM2JiOWE4NzUwMDQ3YjU2MGQxZWM4NmMyYzI0ZTNjOTBlZjU0ZGZlYWEwZCIsImF1ZCI6ImphbWVzIiwiZXhwIjoxNzMwODg2NzEzLCJpYXQiOjE3MzA4ODY0MTMsImF1dGhfdGltZSI6MTczMDg4NjM5OSwiYWNyIjoiZ29hdXRoZW50aWsuaW8vcHJvdmlkZXJzL29hdXRoMi9kZWZhdWx0IiwiYW1yIjpbInB3ZCJdLCJlbWFpbCI6ImphbWVzLXVzZXJAdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJKYW1lcyIsImdpdmVuX25hbWUiOiJKYW1lcyIsInByZWZlcnJlZF91c2VybmFtZSI6ImphbWVzLXVzZXIiLCJuaWNrbmFtZSI6ImphbWVzLXVzZXIiLCJncm91cHMiOlsiZmlhdF9zbWFzaC1tYWlsIl0sImF6cCI6ImphbWVzIiwidWlkIjoiQlozU1VvZ0F5QUQ4YlV6b3BrWkxvRHdEbTk1cDhmYnZLOUQ5bk5aZSJ9.bmW9lbRE59FSCkajKtrL0ukk8uOzhbMminxXFVM6tyHv_x70zY096DuOf7dlCRsPERh_NYG27rPIGsbsAH2YHhwIoE1NLJ24NLnHDjljs7n8qrfB1T6_Sipr0MISkNU5OP5RLBZeh0_BNLhLVL9n8s7cd_dWxWcV9O8Q5hbsTndzjm8Avvi_ckhsmI0RphNQxHSZGMtr2opz_dx-x5PMJsEgTJr0G6Q0fA6cz3cL6UD3AcGCzAMLz3upEGlfMJyHFf88T7c670k500VW3oMoSfU7KskpbwnlbES028MDG1IYvB6esEE7-Dr10hlTuSC_UhJCK1K86-MlPOpfk3YrTp9DFglFQpUtF7P1v8PFZVwOqY1cscvgBEEWkK-qqPzE7qkz7olNZV61mOJIbOcPyrQeKHClQUk9-pIOJfY3Ve438_5eYZ3sQuHCksCthN8hLSmjwe-u2K3uxUTMTcz5zya7Co8im0vycucvgYk_56sbY69RFtW9LK-ZTuMprg3dWUzjYOQKGgQTJBo75I630Jm-VoxEnIU4pWL-njFY-8ISQNvSTvH_SibzL5Wly5oKZcdsTWvvhUZ4DRs2QXBNp1XR1JsS2quZxtC0ejiZ5QWtMwsS22Ni1TtA_A1xv9RBAGKwCUf5u6vf7MQTm0P9P0ozESN9E0_9MYIEJcc3fwA
X-Userinfo: eyJnaXZlbl9uYW1lIjoiSmFtZXMiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqYW1lcy11c2VyIiwiZ3JvdXBzIjpbImZpYXRfc21hc2gtbWFpbCJdLCJhenAiOiJqYW1lcyIsImlzcyI6Imh0dHA6Ly9zc28uZXhhbXBsZS5jb20vYXBwbGljYXRpb24vby9hcHBfc21hc2gtbWFpbC8iLCJhdWQiOiJqYW1lcyIsImlhdCI6MTczMDg4NjQxMywic3ViIjoiOGQ2NWZhNzQ5YzU3NDJhMmJhMTgzM2JiOWE4NzUwMDQ3YjU2MGQxZWM4NmMyYzI0ZTNjOTBlZjU0ZGZlYWEwZCIsInVpZCI6IkJaM1NVb2dBeUFEOGJVem9wa1pMb0R3RG05NXA4ZmJ2SzlEOW5OWmUiLCJlbWFpbCI6ImphbWVzLXVzZXJAdG1haWwuY29tIiwiYXV0aF90aW1lIjoxNzMwODg2Mzk5LCJhY3IiOiJnb2F1dGhlbnRpay5pby9wcm92aWRlcnMvb2F1dGgyL2RlZmF1bHQiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYW1yIjpbInB3ZCJdLCJuYW1lIjoiSmFtZXMiLCJleHAiOjE3MzA4ODY3MTMsIm5pY2tuYW1lIjoiamFtZXMtdXNlciJ9
X-User: 8d65fa749c5742a2ba1833bb9a8750047b560d1ec86c2c24e3c90ef54dfeaa0d


09:46:56.113204 IP 192.168.208.2.http > 192.168.208.4.33306: Flags [P.], seq 1131:1392, ack 9768, win 501, options [nop,nop,TS val 795058015 ecr 657637820], length 261: HTTP: HTTP/1.1 401 Unauthorized
E..9.?@.@..'.........P.............."......
/c._'2..HTTP/1.1 401 Unauthorized
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization, Accept
Access-Control-Max-Age: 86400
content-type: application/json
content-length: 63


09:46:56.113957 IP 192.168.208.4.9080 > 10.0.50.6.52125: Flags [P.], seq 1703:2221, ack 4343, win 501, options [nop,nop,TS val 1169889301 ecr 2504921513], length 518
E..:ej@.@.......
.2.#x....hR...............
E....N..HTTP/1.1 401 Unauthorized
Content-Type: application/json
Content-Length: 63
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization, Accept
Access-Control-Max-Age: 86400
Server: APISIX/3.9.1
Vary: Origin
Apisix-Plugins: ext-plugin-post-req, limit-req, api-breaker, ext-plugin-pre-req, client-control, openid-connect, proxy-rewrite, cors

{"type":"about:blank","status":401,"detail":"Invalid username"}


```

LDAP configuration from authentik 

```
# james-user, users, tmail.com
dn: cn=james-user,ou=users,dc=tmail,dc=com
gidNumber: 2019
cn: james-user
sAMAccountName: james-user
uid: 8d65fa749c5742a2ba1833bb9a8750047b560d1ec86c2c24e3c90ef54dfeaa0d
ak-active: TRUE
name: James
homeDirectory: /home/james-user
sn: James
ak-superuser: FALSE
memberOf: cn=fiat_smash-mail,ou=groups,dc=tmail,dc=com
mail: james-user@tmail.com
displayName: James
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: user
objectClass: posixAccount
objectClass: goauthentik.io/ldap/user
uidNumber: 2019

```

Apache james error 

```
09:46:56.072 [WARN ] o.a.j.j.r.SessionRoutes - Unauthorized
org.apache.james.user.api.InvalidUsernameException: Given Username needs to contain a @domainpart
        at org.apache.james.user.lib.UsersRepositoryImpl.assertDomainPartValidReactive(UsersRepositoryImpl.java:129)
        at org.apache.james.user.ldap.ReadOnlyUsersLDAPRepository.assertValidReactive(ReadOnlyUsersLDAPRepository.java:245)
        at org.apache.james.jmap.http.XUserAuthenticationStrategy.createMailboxSession(XUserAuthenticationStrategy.java:101)
        at java.base/java.util.Optional.map(Unknown Source)
        at org.apache.james.jmap.http.XUserAuthenticationStrategy.createMailboxSession(XUserAuthenticationStrategy.java:96)
        at org.apache.james.jmap.http.Authenticator.lambda$authenticate$0(Authenticator.java:56)
        at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183)
        ... 55 common frames omitted
Wrapped by: org.apache.james.jmap.exceptions.UnauthorizedException: Invalid username
        at org.apache.james.jmap.http.XUserAuthenticationStrategy.lambda$createMailboxSession$3(XUserAuthenticationStrategy.java:102)
        at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3854)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.Operators.error(Operators.java:198)
        at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265)
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
        at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:207)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:335)
        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
        at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerComplete(FluxConcatMapNoPrefetch.java:275)
        at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onComplete(FluxConcatMap.java:889)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:189)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:239)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onComplete(FluxMapFuseable.java:350)
        at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:159)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:260)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2331)
        at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:339)
        at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241)
        at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
        at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
        at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:109)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
        at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:1176)
        at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:481)
        at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:781)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:259)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by chibenwa** [comment]
It's pretty clear: include the email scope in the claim and use it to back the username which for tmail is the username

**Comment by NumeriKa** [comment]
Oh thanks you are right. Already added the email in scope, but miss config in the subject mode in authentik, switch to "Based on the user's email'. Work like a charm.
