### ISSUE TITLE
Error for team mailboxes

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#306]
```
03:15:06.974 [INFO ] o.a.j.m.s.StoreMailboxManager - Mailbox '#private:team-mailbox@localhost:INBOX' not found.
03:15:06.977 [ERROR] o.a.j.e.d.InVmEventDelivery - Error while processing listener
org.apache.james.mailbox.exception.MailboxRoleNotFoundException: Could not find any mailbox with role 'inbox'
	at org.apache.james.mailbox.SystemMailboxesProvider.lambda$findMailbox$0(SystemMailboxesProvider.java:36)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at org.apache.james.mailbox.SystemMailboxesProvider.findMailbox(SystemMailboxesProvider.java:36)
	at org.apache.james.mailbox.spamassassin.SpamAssassinListener.isAppendedToInbox(SpamAssassinListener.java:142)
	at org.apache.james.mailbox.spamassassin.SpamAssassinListener.handleAdded(SpamAssassinListener.java:106)
	at org.apache.james.mailbox.spamassassin.SpamAssassinListener.event(SpamAssassinListener.java:101)
	at org.apache.james.events.EventListener$ReactiveWrapper.lambda$reactiveEvent$0(EventListener.java:67)
	at com.github.fge.lambdas.runnable.RunnableChainer.doRun(RunnableChainer.java:18)
	at com.github.fge.lambdas.runnable.ThrowingRunnable.run(ThrowingRunnable.java:16)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
03:15:06.978 [ERROR] o.a.j.e.d.EventDelivery$Retryer$BackoffRetryer - listener org.apache.james.events.EventListener.ReactiveWrapper exceeded maximum retry(8) to handle event org.apache.james.mailbox.events.MailboxEvents.Added
org.apache.james.mailbox.exception.MailboxRoleNotFoundException: Could not find any mailbox with role 'inbox'
	at org.apache.james.mailbox.SystemMailboxesProvider.lambda$findMailbox$0(SystemMailboxesProvider.java:36)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at org.apache.james.mailbox.SystemMailboxesProvider.findMailbox(SystemMailboxesProvider.java:36)
	at org.apache.james.mailbox.spamassassin.SpamAssassinListener.isAppendedToInbox(SpamAssassinListener.java:142)
	at org.apache.james.mailbox.spamassassin.SpamAssassinListener.handleAdded(SpamAssassinListener.java:106)
	at org.apache.james.mailbox.spamassassin.SpamAssassinListener.event(SpamAssassinListener.java:101)
	at org.apache.james.events.EventListener$ReactiveWrapper.lambda$reactiveEvent$0(EventListener.java:67)
	at com.github.fge.lambdas.runnable.RunnableChainer.doRun(RunnableChainer.java:18)
	at com.github.fge.lambdas.runnable.ThrowingRunnable.run(ThrowingRunnable.java:16)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227)
	... 7 common frames omitted
Wrapped by: reactor.core.Exceptions$RetryExhaustedException: Retries exhausted: 8/8
	at reactor.core.Exceptions.retryExhausted(Exceptions.java:290)
	at reactor.util.retry.RetryBackoffSpec.lambda$static$0(RetryBackoffSpec.java:67)
	at reactor.util.retry.RetryBackoffSpec.lambda$generateCompanion$4(RetryBackoffSpec.java:557)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:375)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onError(MonoUsing.java:260)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:230)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

 -> Understand why the `SystemMailboxesProvider` fails on delegated / team-mailbox INBOX and fix it!

**Comment by chibenwa** [comment]
This happens because `#private:team-mailbox@localhost:INBOX` is looked up...

We need to write a `TMailSystemMailboxesProvider` that, if the username is `team-mailbox` does a TeamMailbpx lookup (with a fallback to `#private`) instead of just a `#private` lookup...
