### ISSUE TITLE
Error DriverTimeoutException when maven test distributed-smtp-integration-tests

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#464]
when running the maven test:
- `tmail-backend/integration-tests/smtp/distributed-smtp-integration-tests`
- `mvn clean test -Dtest=com.linagora.tmail.james.DistributedTeamMailboxSmtpTest`

A error has been throw: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
```
[INFO] Running com.linagora.tmail.james.DistributedTeamMailboxSmtpTest
12:42:30.630 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 0 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:30.633 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 0 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:30.634 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 0 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:32.726 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 1 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:32.727 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 1 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:32.728 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 1 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:34.825 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 2 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:34.827 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 2 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:34.828 [ERROR] o.a.j.e.GroupConsumerRetry - Exception happens when handling event after 2 retries
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:207)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
        at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:35.566 [ERROR] c.r.c.i.ForgivingExceptionHandler - Consumer com.rabbitmq.client.impl.recovery.AutorecoveringChannel$2@60d178cc (amq.ctag-wPq6TjyoeBFMxSZFcYXeYg) method handleDelivery for channel AMQChannel(amqp://guest@127.0.0.1:49222/,14) threw an exception for channel AMQChannel(amqp://guest@127.0.0.1:49222/,14)
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @10315254
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:512)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:368)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:129)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:807)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:477)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:472)
        at org.nustaq.serialization.FSTConfiguration.createMinBinConfiguration(FSTConfiguration.java:229)
        at org.nustaq.serialization.FSTConfiguration.constructJsonConf(FSTConfiguration.java:319)
        at org.nustaq.serialization.FSTConfiguration.createJsonConfiguration(FSTConfiguration.java:301)
        at org.nustaq.serialization.FSTConfiguration.createJsonConfiguration(FSTConfiguration.java:290)
        at org.nustaq.serialization.FSTConfiguration.createJsonConfiguration(FSTConfiguration.java:294)
        at org.apache.mailet.Serializer$FSTSerializer.<clinit>(Serializer.java:578)
        ... 39 common frames omitted
Wrapped by: java.lang.ExceptionInInitializerError: null
        at org.apache.mailet.Serializer$Registry.<clinit>(Serializer.java:79)
        at org.apache.mailet.AttributeValue.findSerializerAndDeserialize(AttributeValue.java:206)
        at org.apache.mailet.AttributeValue.lambda$deserialize$1(AttributeValue.java:202)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.apache.mailet.AttributeValue.lambda$deserialize$2(AttributeValue.java:202)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.apache.mailet.AttributeValue.deserialize(AttributeValue.java:201)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.apache.mailet.AttributeValue.fromJson(AttributeValue.java:191)
        at org.apache.mailet.AttributeValue.fromJsonString(AttributeValue.java:175)
        at org.apache.james.queue.rabbitmq.MailReferenceDTO.lambda$mailMetadata$4(MailReferenceDTO.java:228)
        at com.github.fge.lambdas.consumers.BiConsumerChainer.lambda$sneakyThrow$14(BiConsumerChainer.java:73)
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292)
        at org.apache.james.queue.rabbitmq.MailReferenceDTO.mailMetadata(MailReferenceDTO.java:231)
        at org.apache.james.queue.rabbitmq.MailReferenceDTO.toMailReference(MailReferenceDTO.java:207)
        at org.apache.james.queue.rabbitmq.MailLoader.lambda$load$0(MailLoader.java:50)
        at reactor.core.publisher.MonoCallable.call(MonoCallable.java:92)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:62)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.onNext(FluxMergeSequential.java:237)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
        at reactor.core.publisher.FluxUsing$UsingConditionalSubscriber.onNext(FluxUsing.java:510)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
        at reactor.rabbitmq.Receiver.lambda$null$9(Receiver.java:216)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$2.handleDelivery(AutorecoveringChannel.java:588)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
12:42:45.283 [ERROR] c.d.d.d.i.c.c.r.ReactiveResultSetSubscription - reactor.core.publisher.FluxMap$MapSubscriber@3641cb0f violated the Reactive Streams rule 2.13 by throwing an exception from onNext.
java.lang.NoClassDefFoundError: Could not initialize class org.apache.mailet.Serializer$Registry
        at org.apache.mailet.AttributeValue.findSerializerAndDeserialize(AttributeValue.java:206)
        at org.apache.mailet.AttributeValue.lambda$deserialize$1(AttributeValue.java:202)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.apache.mailet.AttributeValue.lambda$deserialize$2(AttributeValue.java:202)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.apache.mailet.AttributeValue.deserialize(AttributeValue.java:201)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.apache.mailet.AttributeValue.fromJson(AttributeValue.java:191)
        at org.apache.mailet.AttributeValue.fromJsonString(AttributeValue.java:175)
        at org.apache.james.queue.rabbitmq.view.cassandra.EnqueuedMailsDaoUtil.fromByteBuffer(EnqueuedMailsDaoUtil.java:153)
        at org.apache.james.queue.rabbitmq.view.cassandra.EnqueuedMailsDaoUtil.lambda$toAttributes$0(EnqueuedMailsDaoUtil.java:147)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.apache.james.queue.rabbitmq.view.cassandra.EnqueuedMailsDaoUtil.toAttributes(EnqueuedMailsDaoUtil.java:148)
        at org.apache.james.queue.rabbitmq.view.cassandra.EnqueuedMailsDaoUtil.toEnqueuedMail(EnqueuedMailsDaoUtil.java:126)
        at org.apache.james.queue.rabbitmq.view.cassandra.EnqueuedMailsDAO.lambda$selectEnqueuedMails$3(EnqueuedMailsDAO.java:190)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
        at com.datastax.dse.driver.internal.core.cql.reactive.ReactiveResultSetSubscription.doOnNext(ReactiveResultSetSubscription.java:364)
        at com.datastax.dse.driver.internal.core.cql.reactive.ReactiveResultSetSubscription.drain(ReactiveResultSetSubscription.java:236)
        at com.datastax.dse.driver.internal.core.cql.reactive.ReactiveResultSetSubscription.lambda$fetchNextPageAndEnqueue$2(ReactiveResultSetSubscription.java:358)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.setFinalResult(CqlRequestHandler.java:324)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.access$1500(CqlRequestHandler.java:95)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler$NodeResponseCallback.onResponse(CqlRequestHandler.java:655)
        at com.datastax.oss.driver.internal.core.channel.InFlightHandler.channelRead(InFlightHandler.java:257)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

## Note
- Do not forget to remove a line `<groups combine.self="override">BasicFeature</groups>` in pom.xml

**Comment by Arsnael** [comment]
Why it's not throwing on the CI btw? Is it some misconfiguration locally or..?

**Comment by chibenwa** [comment]
> Why it's not throwing on the CI btw? Is it some misconfiguration locally or..?

To quote Tung

> Do not forget to remove a line <groups combine.self="override">BasicFeature</groups> in pom.xml

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-backend/pull/467 to run it on the CI...
