### ISSUE TITLE
ContactsCollection fails to parse "group" email address

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#548]
1. write a test that reproduce
2. delegate parsing to MIME4J, or use it better?

----------------

```
Sujet :	Re: Recensement parc informatique
Date :	Wed, 25 Jan 2023 10:09:00 +0100
De :	alexandre conte [<aconte@linagora.com>](mailto:aconte@linagora.com)
Répondre à :	[aconte@linagora.com](mailto:aconte@linagora.com)
Pour :	[aconte@linagora.com](mailto:aconte@linagora.com)

We were unable to deliver the attached message because of an error in the mail server.

Error message below:
Exception calling com.linagora.tmail.mailets.ContactsCollection: javax.mail.internet.AddressException: Invalid character in local-part (user account) at position 14 in 'destinataires inconnus: ;' in string ``destinataires inconnus: ;'' at position 14
reactor.core.Exceptions$ReactiveException: javax.mail.internet.AddressException: Invalid character in local-part (user account) at position 14 in 'destinataires inconnus: ;' in string ``destinataires inconnus: ;'' at position 14
at reactor.core.Exceptions.propagate(Exceptions.java:396)
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
at reactor.core.publisher.Mono.block(Mono.java:1707)
at reactor.core.scala.publisher.SMono.block(SMono.scala:108)
at reactor.core.scala.publisher.SMono.block$(SMono.scala:107)
at reactor.core.scala.publisher.ReactiveSMono.block(ReactiveSMono.scala:8)
at com.linagora.tmail.mailets.ContactsCollection.service(ContactsCollection.scala:64)
at org.apache.james.mailetcontainer.impl.ProcessorImpl.process(ProcessorImpl.java:81)
at com.github.fge.lambdas.consumers.ConsumerChainer.lambda$sneakyThrow$9(ConsumerChainer.java:73)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
at org.apache.james.mailetcontainer.impl.MailetProcessorImpl.executeProcessingStep(MailetProcessorImpl.java:162)
at org.apache.james.mailetcontainer.impl.MailetProcessorImpl.lambda$service$0(MailetProcessorImpl.java:130)
at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
at org.apache.james.mailetcontainer.impl.MailetProcessorImpl.service(MailetProcessorImpl.java:128)
at org.apache.james.mailetcontainer.lib.AbstractStateCompositeProcessor.handleWithProcessor(AbstractStateCompositeProcessor.java:98)
at org.apache.james.mailetcontainer.lib.AbstractStateCompositeProcessor.service(AbstractStateCompositeProcessor.java:80)
at org.apache.james.mailetcontainer.lib.AbstractStateMailetProcessor.toProcessor(AbstractStateMailetProcessor.java:151)
at org.apache.james.mailetcontainer.impl.MailetProcessorImpl.lambda$executeProcessingStep$7(MailetProcessorImpl.java:167)
at com.github.fge.lambdas.consumers.ConsumerChainer.lambda$sneakyThrow$9(ConsumerChainer.java:73)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
at org.apache.james.mailetcontainer.impl.MailetProcessorImpl.executeProcessingStep(MailetProcessorImpl.java:167)
at org.apache.james.mailetcontainer.impl.MailetProcessorImpl.lambda$service$0(MailetProcessorImpl.java:130)
at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
at org.apache.james.mailetcontainer.impl.MailetProcessorImpl.service(MailetProcessorImpl.java:128)
at org.apache.james.mailetcontainer.lib.AbstractStateCompositeProcessor.handleWithProcessor(AbstractStateCompositeProcessor.java:98)
at org.apache.james.mailetcontainer.lib.AbstractStateCompositeProcessor.service(AbstractStateCompositeProcessor.java:80)
at org.apache.james.mailetcontainer.impl.JamesMailSpooler$Runner.performProcessMail(JamesMailSpooler.java:130)
at org.apache.james.mailetcontainer.impl.JamesMailSpooler$Runner.lambda$processMail$4(JamesMailSpooler.java:122)
at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49)
at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:109)
at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
at reactor.core.publisher.Mono.subscribe(Mono.java:4440)
at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Suppressed: java.lang.Exception: #block terminated with an error
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
... 71 more
Caused by: javax.mail.internet.AddressException: Invalid character in local-part (user account) at position 14 in 'destinataires inconnus: ;' in string ``destinataires inconnus: ;'' at position 14
at org.apache.james.core.MailAddress.parseUnquotedLocalPart(MailAddress.java:524)
at org.apache.james.core.MailAddress.parseUnquotedLocalPartOrThrowException(MailAddress.java:259)
at org.apache.james.core.MailAddress.<init>(MailAddress.java:189)
at org.apache.james.core.MailAddress.<init>(MailAddress.java:304)
at com.linagora.tmail.mailets.ContactsCollection.extractContactField(ContactsCollection.scala:74)
at com.linagora.tmail.mailets.ContactsCollection.$anonfun$extractRecipientsContacts$3(ContactsCollection.scala:71)
at scala.collection.immutable.List.map(List.scala:246)
at scala.collection.immutable.List.map(List.scala:79)
at com.linagora.tmail.mailets.ContactsCollection.extractRecipientsContacts(ContactsCollection.scala:71)
at com.linagora.tmail.mailets.ContactsCollection.$anonfun$service$1(ContactsCollection.scala:60)
at reactor.core.scala.publisher.package$.$anonfun$scalaFunction2JavaFunction$1(package.scala:51)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
at reactor.core.publisher.Mono.block(Mono.java:1706)
... 70 more


Message details:
Subject: Recensement parc informatique
Sent date: Wed Jan 25 09:09:00 UTC 2023
From: alexandre conte [<xxx@linagora.com>](mailto:aconte@linagora.com)
To: destinataires inconnus: ;
Size: 1.5 KiB
``

**Comment by quantranhong1999** [comment]
It seems a standard group email address is in the form `groupName:addr1,addr2,...;`
However, a "blind" group email address (our guy's case) could be used (likely with Thunderbird) with `To` header: `groupName:;` while the actual addresses being set in Bcc (https://bugzilla.mozilla.org/show_bug.cgi?id=83521#c10).

I would handle both of these cases for `ContactsCollection`.
(`javax.mail.internet.InternetAddress` provides group address APIs so it should be well doable.)

**Comment by chibenwa** [comment]
Please prefer using MIME4J !!!!

**Comment by quantranhong1999** [comment]
> Please prefer using MIME4J !!!!

From my side, I could not find any APIs in `MimeMessage` that relates to the group address (Or I miss smth?)
Maybe for now use directly `InternetAddress` API parsing the group and another ticket contribute that to Mime4J?

**Comment by quantranhong1999** [comment]
Oops I mixed up MimeMessage from javax mail and Mime4j. I will check Mime4j tmr.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/550
