### ISSUE TITLE
Starting James with firebase enabled fails

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#800]
```
07:13:48.761 [ERROR] o.a.j.GuiceJamesServer - Fatal error while starting James
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for JmapSettingsRepository was bound.

Requested by:
1  : FirebasePushListener.<init>(FirebasePushListener.scala:30)
      \_ for 3rd parameter jmapSettingsRepository
     at DistributedServer$FirebaseListenerDistributedModule.registerFirebaseListener(DistributedServer.java:317)
      \_ for 2nd parameter
     at DistributedServer$FirebaseListenerDistributedModule.registerFirebaseListener(DistributedServer.java:317)
      \_ installed by: Modules$CombinedModule -> Modules$OverrideModule -> Modules$OverrideModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> DistributedServer$FirebaseListenerDistributedModule

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

1 error

======================
Full classname legend:
======================
DistributedServer$FirebaseListenerDistributedModule: "com.linagora.tmail.james.app.DistributedServer$FirebaseListenerDistributedModule"
FirebasePushListener:                                "com.linagora.tmail.james.jmap.firebase.FirebasePushListener"
JmapSettingsRepository:                              "com.linagora.tmail.james.jmap.settings.JmapSettingsRepository"
Modules$CombinedModule:                              "com.google.inject.util.Modules$CombinedModule"
Modules$OverrideModule:                              "com.google.inject.util.Modules$OverrideModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.apache.james.GuiceJamesServer.start(GuiceJamesServer.java:87)
	at org.apache.james.JamesServerMain.main(JamesServerMain.java:30)
	at com.linagora.tmail.james.app.DistributedServer.main(DistributedServer.java:266)
```

**Comment by quantranhong1999** [comment]
That is because no implementation for JmapSettingRepository has been bound for Distributed server yet. I expect this to be solved after https://github.com/linagora/tmail-backend/issues/786 (with Guice binding)...

**Comment by Arsnael** [comment]
Merged, good catch guys!
