### ISSUE TITLE
EventCalndar/parse failure

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#840]
### Description of the bug

Parsing a microsoft `text/calendar` triggers a not parsable answer:

```
        [
            "CalendarEvent/parse",
            {
                "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
                "notParsable": [
                    "1_4"
                ]
            },
            "c1"
        ]
```

### Reproduction Steps

[office365.eml.txt](https://github.com/linagora/tmail-backend/files/12813500/office365.eml.txt)

And EventCalendar/parse the attachment.

### Expected result

Should be parseable, should not loose timezone

### Additional information

Stacktrace spotted:

```
java.time.DateTimeException: Invalid ID for region-based ZoneId, invalid format: Romance Standard Time
	at java.base/java.time.ZoneRegion.checkName(ZoneRegion.java:152)
	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:117)
	at java.base/java.time.ZoneId.of(ZoneId.java:410)
	at java.base/java.time.ZoneId.of(ZoneId.java:358)
	at java.base/java.time.ZoneId.of(ZoneId.java:314)
	at java.base/java.util.TimeZone.toZoneId0(TimeZone.java:574)
	at java.base/java.util.TimeZone.toZoneId(TimeZone.java:551)
	at com.linagora.tmail.james.jmap.model.CalendarStartField$.$anonfun$from$22(CalendarEventParse.scala:184)
	at com.linagora.tmail.james.jmap.model.CalendarStartField$.$anonfun$from$22$adapted(CalendarEventParse.scala:175)
	at scala.Option.map(Option.scala:242)
	at com.linagora.tmail.james.jmap.model.CalendarStartField$.$anonfun$from$21(CalendarEventParse.scala:175)
	at scala.Option.flatMap(Option.scala:283)
	at com.linagora.tmail.james.jmap.model.CalendarStartField$.from(CalendarEventParse.scala:174)
	at com.linagora.tmail.james.jmap.model.CalendarEventParsed$.fromVEvent(CalendarEventParse.scala:517)
	at com.linagora.tmail.james.jmap.model.CalendarEventParsed$.$anonfun$from$72(CalendarEventParse.scala:513)
	at scala.collection.immutable.List.map(List.scala:246)
	at com.linagora.tmail.james.jmap.model.CalendarEventParsed$.from(CalendarEventParse.scala:513)
	at com.linagora.tmail.james.jmap.model.CalendarEventParsed$.$anonfun$from$69(CalendarEventParse.scala:501)
	at scala.util.Try$.apply(Try.scala:210)
	at com.linagora.tmail.james.jmap.model.CalendarEventParsed$.from(CalendarEventParse.scala:498)
	at com.linagora.tmail.james.jmap.method.CalendarEventParseMethod.$anonfun$toParseResults$3(CalendarEventParseMethod.scala:123)
	at scala.util.Using$.$anonfun$apply$1(Using.scala:262)
	at scala.util.Using$.apply(Using.scala:113)
	at com.linagora.tmail.james.jmap.method.CalendarEventParseMethod.$anonfun$toParseResults$1(CalendarEventParseMethod.scala:123)
```

The VEVENT:

```
BEGIN:VEVENT
ORGANIZER;CN=HAMOUI Fady:mailto:fady.hamoui@docaposte.fr
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=btellier@linagora.com:mailto:btellier@linagora.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=SARR Daouda:mailto:daouda.sarr@docaposte.fr
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=GILABERT Stephane:mailto:stephane.gilabert@docaposte.fr
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=DORMOY Sarah:mailto:sarah.dormoy@docaposte.fr
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=BOUCHENAK Badredine:mailto:badredine.bouchenak@docaposte.fr
DESCRIPTION;LANGUAGE=fr-FR:Hello\n\nPetit point cassandra ☺\n\nPremière 30 minutes avec Daouda.\n\nMerci à tous\n\nFady\n________________________________________________________________________________\nRéunion Microsoft Teams\nParticipez à partir de votre ordinateur\, de votre application mobile ou de l’appareil de la salle\nCliquez ici pour rejoindre la réunion<https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODJmZTU0NzYtOTZhZS00ZjllLTgzY2EtZDU4ODAwMjU4ZjBl%40thread.v2/0?context=%7b%22Tid%22%3a%2280c03608-5f64-40bb-9c70-9394abe6011c%22%2c%22Oid%22%3a%22b1c5e796-470e-4d52-a0cb-ed63246b37c3%22%7d>\nID de la réunion : 348 967 821 107\nCode secret : BmDSqS\nTélécharger Teams<https://www.microsoft.com/en-us/microsoft-teams/download-app> | Rejoindre sur le web<https://www.microsoft.com/microsoft-teams/join-a-meeting>\nRejoindre avec un appareil de visioconférence\nteams@visio.laposte.fr\nID de vidéoconférence : 126 935 800 8\nAutres instructions VTC<https://web.visio.laposte.fr/teams/?conf=1269358008&ivr=teams&d=visio.laposte.fr&ip=178.213.67.162&w>\nOu composer le numéro (audio seulement)\n+33 1 70 99 53 79\,\,517069472#<tel:+33170995379\,\,517069472#>   France\, Paris\nID Conférence Téléphone: 517 069 472#\nRechercher un numéro local<https://dialin.teams.microsoft.com/965c2224-2e7c-4756-a1e8-9546ca00cbc1?id=517069472> | Réinitialiser le code confidentiel<https://dialin.teams.microsoft.com/usp/pstnconferencing>\nPour en savoir plus<https://aka.ms/JoinTeamsMeeting> | Options de réunion<https://teams.microsoft.com/meetingOptions/?organizerId=b1c5e796-470e-4d52-a0cb-ed63246b37c3&tenantId=80c03608-5f64-40bb-9c70-9394abe6011c&threadId=19_meeting_ODJmZTU0NzYtOTZhZS00ZjllLTgzY2EtZDU4ODAwMjU4ZjBl@thread.v2&messageId=0&language=fr-FR>\n________________________________________________________________________________\n\n
UID:040000008200E00074C5B7101A82E00800000000602312E836EDD90100000000000000001000000009C40B24EBC55C49B5E76D3C60DFC74F
SUMMARY;LANGUAGE=fr-FR:[SV] point cassandra
DTSTART;TZID=Romance Standard Time:20230922T160000
DTEND;TZID=Romance Standard Time:20230922T170000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20230922T072808Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=fr-FR:Réunion Microsoft Teams
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:-149514265
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-SKYPETEAMSMEETINGURL:https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODJmZTU0NzYtOTZhZS00ZjllLTgzY2EtZDU4ODAwMjU4ZjBl%40thread.v2/0?context=%7b%22Tid%22%3a%2280c03608-5f64-40bb-9c70-9394abe6011c%22%2c%22Oid%22%3a%22b1c5e796-470e-4d52-a0cb-ed63246b37c3%22%7d
X-MICROSOFT-SCHEDULINGSERVICEUPDATEURL:https://api.scheduler.teams.microsoft.com/teams/80c03608-5f64-40bb-9c70-9394abe6011c/b1c5e796-470e-4d52-a0cb-ed63246b37c3/19_meeting_ODJmZTU0NzYtOTZhZS00ZjllLTgzY2EtZDU4ODAwMjU4ZjBl@thread.v2/0
X-MICROSOFT-SKYPETEAMSPROPERTIES:{\"cid\":\"19:meeting_ODJmZTU0NzYtOTZhZS00ZjllLTgzY2EtZDU4ODAwMjU4ZjBl@thread.v2\"\,\"private\":true\,\"type\":0\,\"mid\":0\,\"rid\":0\,\"uid\":null}
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-LOCATIONS:[{\"DisplayName\":\"Réunion Microsoft Teams\"\,\"LocationAnnotation\":\"\"\,\"LocationUri\":\"\"\,\"LocationStreet\":\"\"\,\"LocationCity\":\"\"\,\"LocationState\":\"\"\,\"LocationCountry\":\"\"\,\"LocationPostalCode\":\"\"\,\"LocationFullAddress\":\"\"}]
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
ACTION:DISPLAY
END:VALARM
END:VEVENT
```

Googled: https://stackoverflow.com/questions/56380472/java-time-datetimeexception-invalid-id-for-region-based-zoneid-invalid-format

Is it as simple as `Romance Standard Time` => `Romance_Standard_Time` ?

**Comment by quantranhong1999** [comment]
> Is it as simple as Romance Standard Time => Romance_Standard_Time ?

It is not simple as that.
`ZoneId.of("Romance_Standard_Time")` does not work. Java ZoneId registry seems not support this one.

I would continue to find a way to interpret this kind of time zone.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/854
