### ISSUE TITLE
opensearch_disabled on tmail

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#901]
Apparently TMail do not start in that mode

CC @Arsnael

**Comment by Arsnael** [comment]
Yes some Guice injection issue. Thank you for creating the task

**Comment by chibenwa** [comment]
```
james                    | 11:37:09.819 [ERROR] o.a.j.GuiceJamesServer - Fatal error while starting James
james                    | com.google.inject.CreationException: Unable to create injector, see the following errors:
james                    | 
james                    | 1) [Guice/MissingConstructor]: No injectable constructor for type ReactorOpenSearchClient.
james                    | 
james                    | class ReactorOpenSearchClient does not have a @Inject annotated constructor or a no-arg constructor.
james                    | 
james                    | Requested by:
james                    | 1  : ReactorOpenSearchClient.class(ReactorOpenSearchClient.java:63)
james                    |      at OSContactAutoCompleteModule$ContactIndexCreator.<init>(OSContactAutoCompleteModule.java:46)
james                    |       \_ for 3rd parameter
james                    |      at OSContactAutoCompleteModule.createIndex(OSContactAutoCompleteModule.java:85)
james                    |       \_ for 1st parameter
james                    |      at OSContactAutoCompleteModule.createIndex(OSContactAutoCompleteModule.java:85)
james                    |       \_ installed by: Modules$CombinedModule -> Modules$OverrideModule -> Modules$OverrideModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$OverrideModule -> OSContactAutoCompleteModule
james                    | 2  : ReactorOpenSearchClient.class(ReactorOpenSearchClient.java:63)
james                    |      at OSEmailAddressContactSearchEngine.<init>(OSEmailAddressContactSearchEngine.java:64)
james                    |       \_ for 1st parameter
james                    |      at OSContactAutoCompleteModule.configure(OSContactAutoCompleteModule.java:59)
james                    |       \_ installed by: Modules$CombinedModule -> Modules$OverrideModule -> Modules$OverrideModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$CombinedModule -> Modules$OverrideModule -> OSContactAutoCompleteModule
james                    | 
james                    | Learn more:
james                    |   https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR
james                    | 
james                    | 1 error
james                    | 
james                    | ======================
james                    | Full classname legend:
james                    | ======================
james                    | Modules$CombinedModule:                          "com.google.inject.util.Modules$CombinedModule"
james                    | Modules$OverrideModule:                          "com.google.inject.util.Modules$OverrideModule"
james                    | OSContactAutoCompleteModule:                     "com.linagora.tmail.james.jmap.module.OSContactAutoCompleteModule"
james                    | OSContactAutoCompleteModule$ContactIndexCreator: "com.linagora.tmail.james.jmap.module.OSContactAutoCompleteModule$ContactIndexCreator"
james                    | OSEmailAddressContactSearchEngine:               "com.linagora.tmail.james.jmap.OSEmailAddressContactSearchEngine"
james                    | ReactorOpenSearchClient:                         "org.apache.james.backends.opensearch.ReactorOpenSearchClient"
james                    | ========================
james                    | End of classname legend:
james                    | ========================
james                    | 
james                    | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589)
james                    | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163)
james                    | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
james                    | 	at com.google.inject.Guice.createInjector(Guice.java:87)
james                    | 	at com.google.inject.Guice.createInjector(Guice.java:69)
james                    | 	at com.google.inject.Guice.createInjector(Guice.java:59)
james                    | 	at org.apache.james.GuiceJamesServer.start(GuiceJamesServer.java:87)
james                    | 	at org.apache.james.JamesServerMain.main(JamesServerMain.java:30)
james                    | 	at com.linagora.tmail.james.app.DistributedServer.main(DistributedServer.java:279)
james exited with code 1
```
